### ISSUE TITLE
Intuitive search handling

### ISSUE THREAD

**Issue by musikisum** [elmu/elmu-web#241]
- It should be possible to paste & copy an entire sentence into the search box and then have the code separate the sentence into individual words (tags).
- Also it should be possible to confirm a tag on the landing page with the space bar (as when entering a tag in the input field on a document page). Then it is possible to type a whole sentence the input field.
- An actualy problem for this szenario is that the search field does not accept words that are not present as tags. Therefore, the search field should also accept words that do not match an existing tag.
- To inform the user that a tag does'nt exist or that with non existing tags nothing will be found, words that do not match a preexisting tag should be marked (for example red). 
- Subsets should give a search result, for example git matches github or Septakkord matches Septakkorde.
- And matching a tag via typing a word should not work case-sensitive.
- It would be helpful if the curser was placed in search field when requesting landing page (like Google).

**Comment by laurentiu-ilici** [comment]
Created a new issue in Jira: https://educandu.atlassian.net/browse/EDU-26
